### PR TITLE
test: add tests for transferOwnership on LSP7

### PR DESCRIPTION
**Pull request by skimaharvey**
## What does this PR introduce? 

Testing of the transferOwnership feature for LSP7.

### CODE REVIEW

**Review by CJ42 — APPROVED** [review]
Nice good job for testing and verifying this!

**Review by b00ste — COMMENTED** [review]
Should we add this tests to the LSP8 as well?

**Comment by CJ42** [comment]
@b00ste yes why not.

**Comment by CJ42** [comment]
@skimaharvey @b00ste I will merge this PR. We can do the same tests for LSP8 in a different PR 🙂

**Pull request merged**
